### ISSUE TITLE
output

### ISSUE THREAD

**Issue by arnoldliaoILMN** [brwnj/umitools#12]
Any guidance on interpreting the output?
processing chromosome 1
1       9       10      4       4
1       11      12      2       1
1       29      30      2       2

**Comment by brwnj** [comment]
This output here starts as a normal bed3 file and represents the before and after counts per region of chromosome 1. From 9 to 10, the count was 4, no duplicate UMIs were present, so the count remained 4. From 11 to 12, one UMI was present, so the count went from 2 to 1.

In this example command:

    umitools rmdup unprocessed.bam out.bam > before_after.bed

The filtered reads were written back to out.bam.
