### ISSUE TITLE
Feature request: Return reads that do not contain a UMI

### ISSUE THREAD

**Issue by jdblischak** [brwnj/umitools#8]
I would like to investigate the reads that do not contain a UMI. I am curious if they are able to be mapped to the genome. Would it be possible to add a flag to `trim.sh` to send reads *without* a UMI to standard error? It would be mutually exclusive with the current `--verbose` flag.

Here's an idea of how it would be implemented on the command line.

```
# Print UMI stats to stderr
umitools trim --verbose unprocessed_fastq NNNNNV 2> stats.txt 1> out.fq

# Print reads w/o UMI to stderr
umitools trim --save-invalid unprocessed_fastq NNNNNV 2> invalid.fq 1> out.fq

# Throw error
umitools trim --verbose --save-invalid unprocessed_fastq NNNNNV > out.fq
```

Both `process_fastq` and `clip_umi` would have to be updated to account for this new option. `clip_umi` would need to return the read instead of just the invalid UMI. If you like this idea, please let me know if you'd like any help implementing and/or testing it.

**Comment by brwnj** [comment]
Feature added in #9.
